"""静态 SQLite 契约的 feature 内兼容导出。

唯一事实来源已下沉到 ``core.shared.sql``；本模块保留 re-export 以兼容
memory feature 内的历史调用方。
"""

from ....shared.sql import (
    DOCUMENTS_TABLE,
    MEMORY_FTS_CLEAR_SQL,
    MEMORY_FTS_COUNT_DISTINCT_DOC_IDS_SQL,
    MEMORY_FTS_CREATE_SQL,
    MEMORY_FTS_DELETE_BY_DOC_ID_SQL,
    MEMORY_FTS_DELETE_BY_JSON_IDS_SQL,
    MEMORY_FTS_INSERT_SQL,
    MEMORY_FTS_OPTIMIZE_SQL,
    MEMORY_FTS_SEARCH_SQL,
    MEMORY_FTS_SELECT_DISTINCT_DOC_IDS_SQL,
    MEMORY_FTS_TABLE,
    SOCIAL_RELATIONS_TABLE,
)

__all__ = [
    "DOCUMENTS_TABLE",
    "MEMORY_FTS_CLEAR_SQL",
    "MEMORY_FTS_COUNT_DISTINCT_DOC_IDS_SQL",
    "MEMORY_FTS_CREATE_SQL",
    "MEMORY_FTS_DELETE_BY_DOC_ID_SQL",
    "MEMORY_FTS_DELETE_BY_JSON_IDS_SQL",
    "MEMORY_FTS_INSERT_SQL",
    "MEMORY_FTS_OPTIMIZE_SQL",
    "MEMORY_FTS_SEARCH_SQL",
    "MEMORY_FTS_SELECT_DISTINCT_DOC_IDS_SQL",
    "MEMORY_FTS_TABLE",
    "SOCIAL_RELATIONS_TABLE",
]
