"""静态 SQLite 契约的兼容导出。"""

from ..features.memory.infrastructure.sql_contract import (
    DOCUMENTS_TABLE,
    MEMORY_FTS_CLEAR_SQL,
    MEMORY_FTS_COUNT_DISTINCT_DOC_IDS_SQL,
    MEMORY_FTS_CREATE_SQL,
    MEMORY_FTS_DELETE_BY_DOC_ID_SQL,
    MEMORY_FTS_DELETE_BY_JSON_IDS_SQL,
    MEMORY_FTS_INSERT_SQL,
    MEMORY_FTS_OPTIMIZE_SQL,
    MEMORY_FTS_SEARCH_SQL,
    MEMORY_FTS_SELECT_DISTINCT_DOC_IDS_SQL,
    MEMORY_FTS_TABLE,
    SOCIAL_RELATIONS_TABLE,
)

__all__ = [
    "DOCUMENTS_TABLE",
    "MEMORY_FTS_CLEAR_SQL",
    "MEMORY_FTS_COUNT_DISTINCT_DOC_IDS_SQL",
    "MEMORY_FTS_CREATE_SQL",
    "MEMORY_FTS_DELETE_BY_DOC_ID_SQL",
    "MEMORY_FTS_DELETE_BY_JSON_IDS_SQL",
    "MEMORY_FTS_INSERT_SQL",
    "MEMORY_FTS_OPTIMIZE_SQL",
    "MEMORY_FTS_SEARCH_SQL",
    "MEMORY_FTS_SELECT_DISTINCT_DOC_IDS_SQL",
    "MEMORY_FTS_TABLE",
    "SOCIAL_RELATIONS_TABLE",
]
