"""共享注入边界常量的旧路径兼容导出。"""

from ..shared.constants import (
    FAKE_TOOL_CALL_ID_PREFIX,
    FAKE_TOOL_CALL_NAME,
    MEMORY_INJECTION_FOOTER,
    MEMORY_INJECTION_HEADER,
)

__all__ = [
    "FAKE_TOOL_CALL_ID_PREFIX",
    "FAKE_TOOL_CALL_NAME",
    "MEMORY_INJECTION_FOOTER",
    "MEMORY_INJECTION_HEADER",
]
