"""自主学习 feature 的纯领域模型。"""

from .auto_learning_actions import (
    CandidateBinding,
    GlobalLearningCandidate,
    aggregation_revision_for,
    is_opaque_id,
    new_opaque_id,
    normalize_weights,
    reduce_global_candidate,
    stable_revision,
    weight_snapshot_hash,
)
from .auto_learning_records import (
    CANDIDATE_REASONS,
    CANDIDATE_STATUSES,
    candidate_status_view,
    claim_view,
    legacy_candidate,
    legacy_intent,
    legacy_publication,
    mapping_records,
    normalize_candidate,
    operation_key,
    parse_datetime,
    publication_view,
    publish_failure,
    rollback_failure,
    safe_reason,
    safe_status,
    utc_now,
)
from .models import (
    FEEDBACK_REASON_CODES,
    FeedbackAdapterKind,
    FeedbackOutcome,
    FeedbackSignalAggregate,
    FeedbackSignalPolicy,
    TrustedFeedbackEvent,
    build_trusted_feedback_event,
)

__all__ = [
    "CANDIDATE_REASONS",
    "CANDIDATE_STATUSES",
    "FEEDBACK_REASON_CODES",
    "CandidateBinding",
    "FeedbackAdapterKind",
    "FeedbackOutcome",
    "FeedbackSignalAggregate",
    "FeedbackSignalPolicy",
    "GlobalLearningCandidate",
    "TrustedFeedbackEvent",
    "aggregation_revision_for",
    "build_trusted_feedback_event",
    "candidate_status_view",
    "claim_view",
    "is_opaque_id",
    "legacy_candidate",
    "legacy_intent",
    "legacy_publication",
    "mapping_records",
    "new_opaque_id",
    "normalize_candidate",
    "normalize_weights",
    "operation_key",
    "parse_datetime",
    "publication_view",
    "publish_failure",
    "reduce_global_candidate",
    "rollback_failure",
    "safe_reason",
    "safe_status",
    "stable_revision",
    "utc_now",
    "weight_snapshot_hash",
]
